# Generated by Django 5.1.2 on 2025-03-16 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        ('platos', '0001_initial'),
        ('productos', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='fk_restaurante',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.restaurantes'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fk_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plato_producto',
            name='fk_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platos_productos', to='pedidos.pedidos'),
        ),
        migrations.AddField(
            model_name='plato_producto',
            name='fk_plato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plato_pedido', to='platos.platos'),
        ),
        migrations.AddField(
            model_name='plato_producto',
            name='fk_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_pedido', to='productos.productos'),
        ),
        migrations.AddField(
            model_name='plato_producto',
            name='fk_restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.restaurantes'),
        ),
    ]
