# Generated by Django 5.1.2 on 2025-03-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('precio_producto', models.IntegerField()),
                ('distribuidor_producto', models.CharField(max_length=50)),
                ('descripcion_producto', models.TextField()),
                ('stock', models.IntegerField(default=10)),
                ('ingresado_en', models.DateTimeField(auto_now_add=True, null=True)),
                ('vence_en', models.DateField(auto_now=True)),
            ],
        ),
    ]
