# Generated by Django 5.1.2 on 2025-03-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fk_restaurante',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.restaurantes'),
        ),
    ]
