# Generated by Django 5.1.2 on 2025-03-16 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platos', '0001_initial'),
        ('productos', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platos',
            name='fk_restaurante',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='users.restaurantes'),
        ),
        migrations.AddField(
            model_name='platos_productos',
            name='fk_plato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='platos.platos'),
        ),
        migrations.AddField(
            model_name='platos_productos',
            name='fk_producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.productos'),
        ),
        migrations.AddField(
            model_name='platos_productos',
            name='fk_restaurante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.restaurantes'),
        ),
    ]
